### ISSUE TITLE
Set Up Networking

### ISSUE THREAD

**Issue by mirpag** [mirpag/SEC-350-Final-Project#1]

**Comment by mirpag** [comment]
- [x] srv1-group12
- [x] vyos1-group12
- [x] centos1-group12
- [x] ubuntu1-group12
- [x] ubuntu2-group12
- [x] wks1-group12
- [x] xubuntu1-group12

**Comment by Tis-arch** [comment]
Netplan Ubuntu 1
network:
    ethernets:
    ens160:
        dhcp4: no
        addresses:
          - 172.16.200.10/28
        gateway4: 172.16.200.2
   version: 2

**Comment by Tis-arch** [comment]
Vyos is networked, but needs securing.
