### ISSUE TITLE
Set up Splunk on Ubuntu

### ISSUE THREAD

**Issue by mirpag** [mirpag/SEC-350-Final-Project#4]

**Comment by Tis-arch** [comment]
Splunk should be set up on ubuntu 1 as of now, will test soon.

**Comment by mirpag** [comment]
Can browse to splunk on srv1-group12 --> 172.16.200.10:8000

**Comment by Tis-arch** [comment]
Set up streams as of 10:49 4/28

**Comment by Tis-arch** [comment]
Streams for ubuntu2 and centos should be set up in terms of log files, ubuntu1's syslog configs should also be good to go.

**Comment by Tis-arch** [comment]
server conf file location /opt/splunk/etc/system/default/server.conf

**Comment by Tis-arch** [comment]
Minimum free desk space fills up immediately after changing the minimum value, even when multiple gigabytes are added.

**Comment by mirpag** [comment]
We pivoted to Graylog. Fixed the installation and got it up on ubuntu-big. Need to get logs sent to graylog.

**Comment by mirpag** [comment]
Index rotation problem on graylog. Need to fix the index rotation configuration.

**Comment by mirpag** [comment]
graylog up and running

**Comment by Tis-arch** [comment]
Graylog is working on UbuntuBig
